import { NextRequest, NextResponse } from 'next/server';

// Mock data para demonstração
const mockData = {
  resumo: {
    necessidadeAporteTotal: 8000.00,
    caixaParaInvestir: 12000.00,
    saldoInicioMes: 45000.00,
    valorAtualizado: 52000.00,
    rendimento: 7000.00,
    rentabilidade: 15.56,
  },
  secoes: [
    {
      nome: "Seguro",
      tipo: "seguro" as const,
      ativos: [
        {
          id: "whole-life-metlife-1",
          nome: "Whole Life Metlife",
          carencia: 24,
          cotacaoResgate: 0.85,
          liquidacaoResgate: 30,
          modalidade: "vida" as const,
          subclasse: "whole_life" as const,
          quantidade: 1.00,
          precoAquisicao: 15000.00,
          valorTotal: 15000.00,
          cotacaoAtual: 0.92,
          valorAtualizado: 16200.00,
          riscoPorAtivo: 5.2,
          percentualCarteira: 31.15,
          objetivo: 25.0,
          quantoFalta: -6.15,
          necessidadeAporte: 0.00,
          rentabilidade: 8.00,
          observacoes: "Seguro de vida inteira com reserva de valor",
        },
        {
          id: "whole-life-icatu-1",
          nome: "Whole Life Icatu",
          carencia: 36,
          cotacaoResgate: 0.78,
          liquidacaoResgate: 45,
          modalidade: "vida" as const,
          subclasse: "whole_life" as const,
          quantidade: 1.00,
          precoAquisicao: 12000.00,
          valorTotal: 12000.00,
          cotacaoAtual: 0.85,
          valorAtualizado: 13000.00,
          riscoPorAtivo: 4.8,
          percentualCarteira: 25.00,
          objetivo: 20.0,
          quantoFalta: -5.00,
          necessidadeAporte: 0.00,
          rentabilidade: 8.33,
          observacoes: "Seguro de vida inteira com foco em crescimento",
        },
      ],
      totalQuantidade: 2.00,
      totalValorAplicado: 27000.00,
      totalValorAtualizado: 29200.00,
      totalRisco: 5.0,
      totalPercentualCarteira: 56.15,
      totalObjetivo: 45.0,
      totalQuantoFalta: -11.15,
      totalNecessidadeAporte: 0.00,
      rentabilidadeMedia: 8.15,
    },
    {
      nome: "Growth (Fundos de Previdência)",
      tipo: "growth_fundos_prev" as const,
      ativos: [
        {
          id: "fundo-prev-vgbl-1",
          nome: "Fundo Prev VGBL",
          carencia: 0,
          cotacaoResgate: 1.00,
          liquidacaoResgate: 1,
          modalidade: "previdencia" as const,
          subclasse: "vgbl" as const,
          quantidade: 1000.00,
          precoAquisicao: 15.50,
          valorTotal: 15500.00,
          cotacaoAtual: 18.20,
          valorAtualizado: 18200.00,
          riscoPorAtivo: 12.5,
          percentualCarteira: 35.00,
          objetivo: 30.0,
          quantoFalta: -5.00,
          necessidadeAporte: 0.00,
          rentabilidade: 17.42,
          observacoes: "Fundo de previdência VGBL com foco em crescimento",
        },
        {
          id: "fundo-prev-pgbl-1",
          nome: "Fundo Prev PGBL",
          carencia: 0,
          cotacaoResgate: 1.00,
          liquidacaoResgate: 1,
          modalidade: "previdencia" as const,
          subclasse: "pgbl" as const,
          quantidade: 500.00,
          precoAquisicao: 12.00,
          valorTotal: 6000.00,
          cotacaoAtual: 13.50,
          valorAtualizado: 6750.00,
          riscoPorAtivo: 8.8,
          percentualCarteira: 12.98,
          objetivo: 15.0,
          quantoFalta: 2.02,
          necessidadeAporte: 2000.00,
          rentabilidade: 12.50,
          observacoes: "Fundo de previdência PGBL com benefício fiscal",
        },
        {
          id: "fundo-prev-multimercado-1",
          nome: "Fundo Prev Multimercado",
          carencia: 0,
          cotacaoResgate: 1.00,
          liquidacaoResgate: 1,
          modalidade: "previdencia" as const,
          subclasse: "fundo_prev" as const,
          quantidade: 200.00,
          precoAquisicao: 25.00,
          valorTotal: 5000.00,
          cotacaoAtual: 28.50,
          valorAtualizado: 5700.00,
          riscoPorAtivo: 15.2,
          percentualCarteira: 10.96,
          objetivo: 10.0,
          quantoFalta: -0.96,
          necessidadeAporte: 0.00,
          rentabilidade: 14.00,
          observacoes: "Fundo multimercado para diversificação",
        },
      ],
      totalQuantidade: 1700.00,
      totalValorAplicado: 26500.00,
      totalValorAtualizado: 30650.00,
      totalRisco: 12.2,
      totalPercentualCarteira: 58.94,
      totalObjetivo: 55.0,
      totalQuantoFalta: -3.94,
      totalNecessidadeAporte: 2000.00,
      rentabilidadeMedia: 14.64,
    },
  ],
  totalGeral: {
    quantidade: 1702.00,
    valorAplicado: 53500.00,
    valorAtualizado: 59850.00,
    risco: 8.6,
    objetivo: 100.0,
    quantoFalta: -15.09,
    necessidadeAporte: 2000.00,
    rentabilidade: 11.87,
  },
  alocacaoAtivo: [
    { nome: "Fundo Prev VGBL", percentual: 35.00, valor: 18200.00 },
    { nome: "Whole Life Metlife", percentual: 31.15, valor: 16200.00 },
    { nome: "Whole Life Icatu", percentual: 25.00, valor: 13000.00 },
    { nome: "Fundo Prev PGBL", percentual: 12.98, valor: 6750.00 },
    { nome: "Fundo Prev Multimercado", percentual: 10.96, valor: 5700.00 },
  ],
  tabelaAuxiliar: [
    { nome: "Fundo Prev PGBL", cotacaoAtual: 13.50, necessidadeAporte: 2000.00, loteAproximado: 148.15 },
  ],
};

export async function GET(request: NextRequest) {
  try {
    // Simula delay de rede
    await new Promise(resolve => setTimeout(resolve, 500));
    
    return NextResponse.json(mockData);
  } catch (error) {
    console.error('Erro ao buscar dados de previdência e seguros:', error);
    return NextResponse.json(
      { error: 'Erro interno do servidor' },
      { status: 500 }
    );
  }
}

