import { NextResponse } from 'next/server';

// Mock data para demonstração
const mockData = {
  resumo: {
    necessidadeAporteTotal: 5000.00,
    caixaParaInvestir: 15000.00,
    saldoInicioMes: 25000.00,
    valorAtualizado: 28000.00,
    rendimento: 3000.00,
    rentabilidade: 12.00,
  },
  secoes: [
    {
      nome: "Moedas & Metais",
      tipo: "moedas_metais" as const,
      regiao: "brasil" as const,
      ativos: [
        {
          id: "usdbrl-1",
          ticker: "USDBRL",
          nome: "Dólar Americano",
          tipo: "moeda" as const,
          regiao: "brasil" as const,
          indiceRastreado: "dolar",
          quantidade: 1000.00,
          precoAquisicao: 5.20,
          valorTotal: 5200.00,
          cotacaoAtual: 5.45,
          valorAtualizado: 5450.00,
          riscoPorAtivo: 8.5,
          percentualCarteira: 19.46,
          objetivo: 15.0,
          quantoFalta: -4.46,
          necessidadeAporte: 0.00,
          rentabilidade: 4.81,
          observacoes: "Reserva de emergência em dólar",
        },
        {
          id: "ouro-1",
          ticker: "OURO",
          nome: "Ouro",
          tipo: "metal" as const,
          regiao: "internacional" as const,
          indiceRastreado: "ouro",
          quantidade: 2.5,
          precoAquisicao: 180.00,
          valorTotal: 450.00,
          cotacaoAtual: 195.00,
          valorAtualizado: 487.50,
          riscoPorAtivo: 12.3,
          percentualCarteira: 1.74,
          objetivo: 5.0,
          quantoFalta: 3.26,
          necessidadeAporte: 1000.00,
          rentabilidade: 8.33,
          observacoes: "Hedge contra inflação",
        },
      ],
      totalQuantidade: 1002.5,
      totalValorAplicado: 5650.00,
      totalValorAtualizado: 5937.50,
      totalRisco: 10.4,
      totalPercentualCarteira: 21.20,
      totalObjetivo: 20.0,
      totalQuantoFalta: -1.20,
      totalNecessidadeAporte: 1000.00,
      rentabilidadeMedia: 6.57,
    },
    {
      nome: "ETF's Estados Unidos",
      tipo: "etf_estados_unidos" as const,
      regiao: "estados_unidos" as const,
      ativos: [
        {
          id: "etha-1",
          ticker: "ETHA",
          nome: "Ethereum ETF",
          tipo: "criptomoeda" as const,
          regiao: "estados_unidos" as const,
          indiceRastreado: "ethereum",
          quantidade: 50.00,
          precoAquisicao: 25.00,
          valorTotal: 1250.00,
          cotacaoAtual: 28.50,
          valorAtualizado: 1425.00,
          riscoPorAtivo: 25.8,
          percentualCarteira: 5.09,
          objetivo: 10.0,
          quantoFalta: 4.91,
          necessidadeAporte: 1500.00,
          rentabilidade: 14.00,
          observacoes: "Exposição a Ethereum via ETF",
        },
        {
          id: "ibit-1",
          ticker: "IBIT",
          nome: "Bitcoin ETF",
          tipo: "criptomoeda" as const,
          regiao: "estados_unidos" as const,
          indiceRastreado: "bitcoin",
          quantidade: 30.00,
          precoAquisicao: 45.00,
          valorTotal: 1350.00,
          cotacaoAtual: 52.00,
          valorAtualizado: 1560.00,
          riscoPorAtivo: 30.2,
          percentualCarteira: 5.57,
          objetivo: 15.0,
          quantoFalta: 9.43,
          necessidadeAporte: 2500.00,
          rentabilidade: 15.56,
          observacoes: "Exposição a Bitcoin via ETF",
        },
        {
          id: "btcusd-1",
          ticker: "BTCUSD",
          nome: "Bitcoin Direto",
          tipo: "criptomoeda" as const,
          regiao: "internacional" as const,
          indiceRastreado: "bitcoin",
          quantidade: 0.15,
          precoAquisicao: 45000.00,
          valorTotal: 6750.00,
          cotacaoAtual: 52000.00,
          valorAtualizado: 7800.00,
          riscoPorAtivo: 35.5,
          percentualCarteira: 27.86,
          objetivo: 20.0,
          quantoFalta: -7.86,
          necessidadeAporte: 0.00,
          rentabilidade: 15.56,
          observacoes: "Bitcoin direto em carteira",
        },
        {
          id: "voo-1",
          ticker: "VOO",
          nome: "S&P 500 ETF",
          tipo: "outro" as const,
          regiao: "estados_unidos" as const,
          indiceRastreado: "sp500",
          quantidade: 20.00,
          precoAquisicao: 400.00,
          valorTotal: 8000.00,
          cotacaoAtual: 420.00,
          valorAtualizado: 8400.00,
          riscoPorAtivo: 15.2,
          percentualCarteira: 30.00,
          objetivo: 25.0,
          quantoFalta: -5.00,
          necessidadeAporte: 0.00,
          rentabilidade: 5.00,
          observacoes: "Exposição ao S&P 500",
        },
      ],
      totalQuantidade: 100.15,
      totalValorAplicado: 17350.00,
      totalValorAtualizado: 19185.00,
      totalRisco: 26.7,
      totalPercentualCarteira: 68.52,
      totalObjetivo: 70.0,
      totalQuantoFalta: 1.48,
      totalNecessidadeAporte: 4000.00,
      rentabilidadeMedia: 10.60,
    },
  ],
  totalGeral: {
    quantidade: 1102.65,
    valorAplicado: 23000.00,
    valorAtualizado: 25122.50,
    risco: 18.55,
    objetivo: 90.0,
    quantoFalta: 0.28,
    necessidadeAporte: 5000.00,
    rentabilidade: 9.23,
  },
  alocacaoAtivo: [
    { ticker: "VOO", percentual: 30.00, valor: 8400.00 },
    { ticker: "BTCUSD", percentual: 27.86, valor: 7800.00 },
    { ticker: "USDBRL", percentual: 19.46, valor: 5450.00 },
    { ticker: "IBIT", percentual: 5.57, valor: 1560.00 },
    { ticker: "ETHA", percentual: 5.09, valor: 1425.00 },
    { ticker: "OURO", percentual: 1.74, valor: 487.50 },
  ],
  tabelaAuxiliar: [
    { ticker: "OURO", cotacaoAtual: 195.00, necessidadeAporte: 1000.00, loteAproximado: 5.13 },
    { ticker: "ETHA", cotacaoAtual: 28.50, necessidadeAporte: 1500.00, loteAproximado: 52.63 },
    { ticker: "IBIT", cotacaoAtual: 52.00, necessidadeAporte: 2500.00, loteAproximado: 48.08 },
  ],
};

export async function GET() {
  try {
    // Simula delay de rede
    await new Promise(resolve => setTimeout(resolve, 500));
    
    return NextResponse.json(mockData);
  } catch (error) {
    console.error('Erro ao buscar dados de moedas e criptomoedas:', error);
    return NextResponse.json(
      { error: 'Erro interno do servidor' },
      { status: 500 }
    );
  }
}

